[gcp_service_account]
type = "service_account"
project_id = "protean-booth-339219"
private_key_id = "15fe4d7f69d5d885099f6f6748228cc4dc4dc8ca"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDTH3KfmEHVld7y
je81U5IfoYcPT8aYJt2KzncDXTbf5sPqwaFwPaRiV6ZccKwRPxncaaHNQTtrYnAA
Z+grAWdQJtlRgPRkgBah3OJXSqpPScJ8Xkv4MGxZpoB4GTaLolqu8IMNtwRJxTOp
7W58nQgpB8uM5ZL1retb6NdO+3GPlOF/uhlv4owPvND7x4wLQv1aerz71w2H+svn
QD6G4vfN6h4bhVL9JBadmF+DqINHMLUzsMHHZcwDv4jwP0aZgtsBMtuPFW70fqrC
ShSHM9dweaCAc67L23ADn+5fOgzWhoQN4vy5F9STAGobtBB/ECMMHT+suTvjmtlB
mExHJgqZAgMBAAECggEAEE0MeHZ07YJcYVBZ3hKypMmVLYv50qlRkBRKoSezLcza
EggFqIPB66vxLDsGNhtaqlI89tBTaletO9gfV3liGjtdqorb6TSbSr/Mzsj05xlU
BcPxdrDPyjOZFhd68YNwIAjG/anvZVNvc+6MCjLFEgdIN/vz1w9TgwMH43vLnrZ6
ltutj+BMab/7H3lQhX+qvNE8oWUgrNGSwojknImtnYDwKNfVPq7li9psdoxg11in
94iyd23U/MKM0oCcjXZX31Qu9dL2teyHFD+N2lEqHfZYuhv5gA9fW5jdxqs3AxQi
6TlDOSY5eL93NeCd3q4EI0cMuh9PuRf02DjWFKgiuQKBgQD8DQhV0G/Gk1GKcPrP
eNSBGrjOlJBpkyYrSsHHsL3A1y/olQ+1gNVwgGr6eUD5CaKemewuzdBrdFG9YmQM
fLEIDdHI6UVgrfbzi8RVezT0BzmDLKgsbN7RVVPE110zP0UHDbr5MCAqXjoHhaGO
P0Iv2OWObG7lPaak/ZXBFMKCvQKBgQDWbkEPNBEsvYBnYM/skTU2asc6p5Kf+q/E
iLap5R0405J8maAdpAfxySnnnjTPn5WGtakes5V5YzGC8/yMBkLeutC9A2S5iE/c
4Yw5q2yxBA+5EPIA7oDv2PoKz8dQctBvLe69IiS3+g7+eWEDi58HBoCV7n2po7gF
RjW+XJzzDQKBgHsohxUfZy6Zl3NVJ0ivWu7GttzCPRpJO5JV0gAYPW/39cHo7Ccd
D64MIbnH+9Z0PdDPl1d7W8bVrIckh4yOdRZhYkuQqETIXG2+sq2uKT7ANPsCnB4x
CGMzFV6OeUzsMndy3xSZzm3FYwd/5WQTRu0IR4rjMwCysjXWbxFMaorlAoGBAMGA
61sR7HHIbMhdmCTugOujfjhTIkEWE2myycwVQsKWQroIVHKLJNQvaY5nuVant2LC
KmTXQIszVWnMTdn6iHvAcEAxgMLg3NkB/O3J4aL4fEvQm+L1WAuZbUM2b7IMekXq
WGf7GNGhaciAtmhhpdfMKVujxWjBon239yXbI5M9AoGBALdYOGN3mLR6lf0ZbkcV
5kFJpOPwr/NgwqwSJIP1hRBU9ZacTKY0UqxfJPAtVuREM6+DyLgbeViMMIziAAZY
TuJi3iBYn0cV9mLchj+fa+RWJZvXZvhtwvwhYqk5r/GR6sBa39XjAs7XirakOBeE
jHBepN2E1G3mVEWFN5MlozLH
-----END PRIVATE KEY-----"""
client_email = "keenan@protean-booth-339219.iam.gserviceaccount.com"
client_id = "107376933325900328553"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/keenan%40protean-booth-339219.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
